### PR TITLE
Announcement of PyHEP 2019

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
FYI @benkrikler.

@graeme-a-stewart, I wasn't sure whether you wanted to have an orange banner too, so created one just in case. Maybe the end-date should be adapted?

### CODE REVIEW

**Comment by benkrikler** [comment]
Ah thanks @eduardo-rodrigues! I was just working on this as well, but you beat me to it :slightly_smiling_face:.  The text looks good to me, it's the same as the announcement itself, right?

**Comment by eduardo-rodrigues** [comment]
Sorry @benkrikler, somehow I got the impression I would do it in the end, since you are heavy on constraints these days!
Yes, it's the email text minus some "headers and footers".

**Comment by eduardo-rodrigues** [comment]
Pinging just in case this slipped you eyes, @graeme-a-stewart.

**Comment by graeme-a-stewart** [comment]
Thanks @eduardo-rodrigues - looks good. I am not sure that the event announcement will really be seen, but it does no harm.

**Pull request merged**
