### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Update centre column on website and SG membership

### CODE REVIEW

**Review by eduardo-rodrigues — APPROVED** [review]
Looks all good :+1:.

**Comment by graeme-a-stewart** [comment]
Thanks @eduardo-rodrigues !

**Comment by hegner** [comment]
Did not realize you took me off now with that PR... keep going and all the best for the future!

**Comment by graeme-a-stewart** [comment]
Yeah, it was rather a revamp which was overdue. Of course we are hugely grateful to all that you contributed to the HSF over the years @hegner 🙏. Best of luck with all your future endeavours! 🚀

**Pull request merged**
