### PR TITLE
[GSOC'22] Final blog update for Geant4-FastSim GSOC submission

### PR DESCRIPTION
**Pull request by prikmm**
@DalilaSalamani Please review

### CODE REVIEW

**Comment by DalilaSalamani** [comment]
@prikmm I put here few comments. Please work on reducing the length of the blog to have a summarised, overview version of the project.

- Memory footprint reduction pipeline picture can be removed 
- when you mention "g4fastsim is broken into 2 parts - Training and Inference" here you can first mention Par04 so you can use it later on
- +1 for the Geant4 FastSim model optimisation pipeline
- Remove the section where you mention the 5 components without explaining what they are as you explain them afterwards
- The section Parameters can be removed (we can have it in our website)
- The content of the Macro file can be also dropped here (you can just show few custom commands), you put a link of that macro so that would be sufficient.
- Not sure why the "Complete Pipeline Image" it has the same content as the one at the top, you can drop it

**Comment by prikmm** [comment]
@DalilaSalamani Updated blog

**Review by DalilaSalamani — APPROVED** [review]

**Review by agheata — CHANGES_REQUESTED** [review]
@prikmm please fix the conflict locally and push again your branch, applying also the suggested changes, otherwise your avatar is not visible and some figures are too big

**Comment by agheata** [comment]
Ping @prikmm

**Comment by prikmm** [comment]
@agheata Really sorry for the delay! I have made the requested the changes.

**Review by agheata — APPROVED** [review]

**Pull request merged**
