### PR TITLE
Add icons to navbar

### PR DESCRIPTION
**Pull request by klieret**
Not sure about this, but I was playing around with having icons in the navbar, e.g.

image

might be a bit cluttered

### CODE REVIEW

**Comment by hegner** [comment]
looks quite nice!

**Review by hegner — APPROVED** [review]

**Comment by hegner** [comment]
@graeme-a-stewart - what's your take on this? The code change itself is trivial

**Comment by eduardo-rodrigues** [comment]
Looks good to me too 👍 .

**Comment by graeme-a-stewart** [comment]
Hi - thanks @klieret, I do like the idea. As @eduardo-rodrigues said I think it looks better with a little more space between the icon and the text, which I added on the last commit (I don't know if there's a better way than `&nbsp;` but I am not a CSS person.

**Comment by graeme-a-stewart** [comment]
There is one weirdness still remaining though - the bottom margin between the HSF on the LHS and the rest of the icons are now misaligned by a few pixels. Does anyone know how to fix that?

Screen Shot 2021-05-31 at 09 56 11

**Review by graeme-a-stewart — CHANGES_REQUESTED** [review]
Still need to fix misalignment

**Comment by klieret** [comment]
I can take a look later this week again. Perhaps I can figure out the alignment issue

**Comment by klieret** [comment]
The issue of the misalignment is due to conflicting padding settings in `hsf.css`:

```css
/* The logo */
.navbar-brand {
    height: 40px;
    padding: 12.5px 15px;
    font-size: 15px;
}

/* This is the rest of the items */
.navbar-nav > li > a {
    padding-top: 9.5px;
    padding-bottom: 9.5px;
}
```

let me fix that

**Comment by klieret** [comment]
Screenshot from 2021-06-26 11-43-32

**Review by graeme-a-stewart — APPROVED** [review]

**Comment by graeme-a-stewart** [comment]
Thanks @klieret - the fix is perfect 👍

**Pull request merged**
