### PR TITLE
Add CSBS reference and DOI for the CWP Roadmap

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Update the CWP page to reference the paper as published in CSBS

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
> I would give the full citation here, I mean atop the link you provide under "Citation". So
> 
> The HEP Software Foundation, Albrecht, J., Alves, A.A. et al. Comput Softw Big Sci (2019) 3: 7. https://doi.org/10.1007/s41781-018-0018-8

Done - are you sure about the abbreviated journal name? I am never certain about how those are generated.

**Comment by eduardo-rodrigues** [comment]
I'm not 100% sure. I looked a bit online and could not find an alternative spelling, though I agree the above looks a wee odd. I would go for the slightly changed format

The HEP Software Foundation, Albrecht, J. et al., Comput Softw Big Sci (2019) 3, 7. https://doi.org/10.1007/s41781-018-0018-8

**Comment by eduardo-rodrigues** [comment]
Sorry for the pain.

Else this can be merged.

**Comment by graeme-a-stewart** [comment]
Are you saying you would not include the title of the article in the reference? That seems weird to me.

Why don't you modify the PR with how you think it should be? I not sure I am quite translating your comments into the markdown properly.

**Comment by eduardo-rodrigues** [comment]
Fair enough, @graeme-a-stewart.
For once I touched the file directly on GitHub; hope it's OK. I reckon this is good to go online.

**Comment by graeme-a-stewart** [comment]
> Fair enough, @graeme-a-stewart.
> For once I touched the file directly on GitHub; hope it's OK. I reckon this is good to go online.

But in this case it's pretty safe, because you're making a commit in my branch, not on the master.

Certainly looks good to me now, so merge in at your leisure. And thanks!

**Pull request merged**
