### PR TITLE
chore: update PyHEP conveners

### PR DESCRIPTION
**Pull request by jpivarski**
Let me know if any corrections are necessary, @eduardo-rodrigues, @oshadura, @matthewfeickert, @nikoladze, and @graeme-a-stewart. Thanks!

### CODE REVIEW

**Review by matthewfeickert — APPROVED** [review]
LGTM. Thanks @jpivarski!

**Review by eduardo-rodrigues — APPROVED** [review]
Thanks.

**Comment by eduardo-rodrigues** [comment]
I made a couple of changes. Correct @oshadura that you co-convened the 2 years I noted, right? I can merge later as soon as I get the confirmation.

**Comment by oshadura** [comment]
@eduardo-rodrigues thanks a lot! Yes everything is correct.

**Pull request merged**
