### PR TITLE
GSoC 2022 proposal for Geant4 performance data visualization

### PR DESCRIPTION
**Pull request by amadio**

### CODE REVIEW

**Review by agheata — CHANGES_REQUESTED** [review]
The proposal looks good and renders correctly. We just need a backup mentor.

**Review by graeme-a-stewart — APPROVED** [review]
@amadio if you need a backup mentor I can help

**Comment by amadio** [comment]
Thank you for the offer, @graeme-a-stewart. Bernhard kindly accepted to be a backup mentor, so I have added him and pushed again.

**Comment by amadio** [comment]
Forgot a `mailto:` in the link, fixed now.

**Review by agheata — APPROVED** [review]

**Comment by amadio** [comment]
And another `mailto:` fixed...

**Comment by aflp91** [comment]
It was said the mentor list should be (last name?) ordered?

**Comment by agheata** [comment]
True, this will be always a source of annoyance and conflicts when we will have concurrent PR's. We can either sort ourselves at the end or make this automatic based on the content of the `Mentors` section (which I don't know how to do...)

**Pull request merged**
