### PR TITLE
Add QR codes for HSF and PyHEP

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
It would be ideal to have somewhere a sentence saying we have this material for presentations but I haven't found the perfect place for it. Ideas?

### CODE REVIEW

**Review by hegner — APPROVED** [review]

**Comment by hegner** [comment]
I think we can just put it onto our next presentations ourselves to spread it. On the website I would not know a good place - maybe the get involved page?

**Comment by eduardo-rodrigues** [comment]
An alternative would be to add a link at https://hepsoftwarefoundation.org/organization/presentations.html to a page on resources for presentations. Let's see how things go in the future and if we have more resources for presentations.

**Comment by hegner** [comment]
That's a good idea. Actually we could as well link the usual template there

**Comment by eduardo-rodrigues** [comment]
> That's a good idea. Actually we could as well link the usual template there

OK, to wrap the week I tried to give this a go, see PR https://github.com/HSF/hsf.github.io/pull/1279 :).

**Pull request merged**
