### PR TITLE
Add GSoC project for Julia ML

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Google Summer of Code project for machine learning in Julia

### CODE REVIEW

**Review by vvolkl — APPROVED** [review]
Very nice, thanks! Draft looks good to me.

**Comment by hegner** [comment]
@graeme-a-stewart - still waiting for Pere?

**Comment by graeme-a-stewart** [comment]
Pere and Piyush signed off, so this is now good to go!

**Comment by hegner** [comment]
@graeme-a-stewart - thanks

**Pull request merged**
