### PR TITLE
Added blog page connected to Season of Docs 2020, including 2 blogs.

### PR DESCRIPTION
**Pull request by agheata**
This is the first attempt at a blog page, connected to our Season of Docs main page. I added the blogs of two technical writers, two more will be added after the long-running projects are evaluated. Using this we can ask future contributors to make a PR for their blog.

### CODE REVIEW

**Review by aflp91 — APPROVED** [review]
Looks great!

**Comment by agheata** [comment]
Note that I added also the announcement for the call for GSDocs 2021

**Comment by agheata** [comment]
@graeme-a-stewart can you have a look if the format for the blog page is convenient?

**Review by xvallspl — APPROVED** [review]

**Comment by agheata** [comment]
Let's merge this and do improvements if needed in a separate PR

**Comment by graeme-a-stewart** [comment]
@agheata - I had time to take a look and it seemed good to me. Apologies for not having reviewed here.

**Pull request merged**
