### PR TITLE
Insufficient bottom margin #1472

### PR DESCRIPTION
**Pull request by Hrittik20**

### CODE REVIEW

**Comment by gunjjoshi** [comment]
Don't just hurry to make a PR. You can always discuss with the community first, for the issue. Have some basic ethics, don't just overwhelm to contribute for gsoc.

**Comment by Hrittik20** [comment]
Sorry, I saw that there was no update on that issue for some time so I just contributed but I should have disscussed it before making a PR. Wont happen again

**Review by klieret — CHANGES_REQUESTED** [review]
To me that does not look very convincing. 

image

I think @gunjjoshi meant only the bottom margin which is indeed somewhat small.

**Comment by Hrittik20** [comment]
@klieret should I do another PR and fix it?

**Comment by klieret** [comment]
You can either create a new PR or add another commit here (the commits are git squashed anyway)

**Comment by klieret** [comment]
Thank you!

**Review by klieret — APPROVED** [review]

**Pull request merged**
