### PR TITLE
Add more schools to training page. 

### PR DESCRIPTION
**Pull request by GuillermoFidalgo**

### CODE REVIEW

**Comment by GuillermoFidalgo** [comment]
@graeme-a-stewart  I have added two school links.

**Comment by graeme-a-stewart** [comment]
Hi @GuillermoFidalgo - this is all good, thanks.

Can I ask you to make these PRs **not** using your master branch. Keep your master branch in sync with the upstream one, then create a new branch with (only) the changes you want to make and create the PR from that branch. Never merge non-fast-forward changes from upstream/master into your fork - always rebase instead. This is to avoid what we have now where you only change 2-3 files, but the commit history of your master branch is huge, compared to upstream.

The workflow we use is called GitHub flow and there is a survival guide here that Michel wrote:

<https://hepsoftwarefoundation.org/github-beginners.html>

There are very strong reasons for ensuring that named branches between your fork and upstream always remain in sync. So always use new branches to do 'development' work.

**Comment by GuillermoFidalgo** [comment]
Thanks for accepting the changes. I apologize as I did not realize this was occurring since I am not GitHub expert.  Will take these steps from now on.

**Comment by graeme-a-stewart** [comment]
Thanks @GuillermoFidalgo! No need to apologise, it takes a while to get your head wrapped around git!

**Pull request merged**
