### PR TITLE
Fix technical note links and mailto URLs

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
Technical notes moved in the GitHub repo, so we shoudl use persistent URLs to
refer to their "development" status, recognising that this will happen.

Upload final naming PDF to this site as well (it's small).

Fix a couple of email links that had been written without mailto:

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
@hegner - I set a final review date for the project best practices (end of the month). Is that ok?

**Comment by hegner** [comment]
@graeme-a-stewart - fine with me. Thanks. Would have been easier if you would have accepted the old #368

**Comment by graeme-a-stewart** [comment]
Woops - apparently I forgot about #368. Silly me.

I guess we should take this PR as it also fixes the links in the meeting minutes.

**Comment by graeme-a-stewart** [comment]
I see this needs one more fix... don't merge yet

**Comment by graeme-a-stewart** [comment]
Grrrr, now I deleted a branch that we referred to in the minutes. Fixing that now too...

**Comment by graeme-a-stewart** [comment]
Yes, it's ready now.

**Comment by graeme-a-stewart** [comment]
OK, let me just accept this one myself then (before the meeting this afternoon)

**Pull request merged**
