### PR TITLE
Homepage banner + PyHEP 2021 post-workshop update

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
As per our email exchanges :-).

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Scary, the link checker says - correctly - that https://chep2018.org/ is not accessible :S.

**Comment by graeme-a-stewart** [comment]
> Scary, the link checker says - correctly - that https://chep2018.org/ is not accessible :S.

Oh, I will let Peter and Latchezar know - I hope they can still fix it...

**Comment by eduardo-rodrigues** [comment]
> > Scary, the link checker says - correctly - that https://chep2018.org/ is not accessible :S.
> 
> Oh, I will let Peter and Latchezar know - I hope they can still fix it...

BTW, when talking to them do request that HTTPS is preferred, at which point we then update our links to the website, which still use HTTP.

**Comment by graeme-a-stewart** [comment]
I think `https` is supprted fine (when it's working) - that's the link we used for the CHEP2021 proceeidngs.

**Review by graeme-a-stewart — APPROVED** [review]
LGTM - thanks @eduardo-rodrigues !

**Pull request merged**
