### PR TITLE
Add GSoC proposal for ATLAS raw data compression study

### PR DESCRIPTION
**Pull request by maszyman**
cc @gemmeren

### CODE REVIEW

**Review by vvolkl — APPROVED** [review]
Nice! Thanks for the project submission.

**Review by vvolkl — CHANGES_REQUESTED** [review]
Ah, one small request: can you add your names to the list of mentors, and check that there are descriptions for ATLAS?

See https://github.com/HSF/hsf.github.io/pull/1487/files for a template, to find the files that need to be changed.

**Review by vvolkl — APPROVED** [review]

**Comment by maszyman** [comment]
Thanks for proceeding with other updates you requested. Are those logo files already available?

**Comment by vvolkl** [comment]
No worries! Yes, since the descriptions were already available, the logos should be under images/ in the top level directory, those don't need to be copied.

**Comment by vvolkl** [comment]
Do you want to wait for confirmation from your co-mentor or should I go ahead and merge?

**Comment by maszyman** [comment]
You can merge. Many thanks!

**Pull request merged**
