### PR TITLE
Final Ganga 2022 blog by Giorgos Apostolopoulos

### PR DESCRIPTION
**Pull request by joj0s**
This PR includes my updated blog for the Ganga project - GSoC 2022.

### CODE REVIEW

**Comment by agheata** [comment]
@joj0s it looks fine to me, but I need an OK from your mentor

**Comment by egede** [comment]
> @egede Could you please approve this PR?

I am afraid that I do not have permission. @graeme-a-stewart @wdconinc can you help.

**Comment by agheata** [comment]
> > @egede Could you please approve this PR?
> 
> I am afraid that I do not have permission. @graeme-a-stewart @wdconinc can you help.

@egede a simple OK comment here will do in case you don't request changes

**Comment by egede** [comment]
All OK from me

**Review by agheata — APPROVED** [review]
LGTM

**Pull request merged**
