### PR TITLE
Minutes of coordination meeting Sep. 12 2024

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi. I see everyone is rather busy. Since this is largely a no-brainer I will merge later today unless I hear back from anyone :-).

**Comment by graeme-a-stewart** [comment]
I am just having a look now!

**Comment by graeme-a-stewart** [comment]
I found a few small points - now LGTM!

**Review by graeme-a-stewart — APPROVED** [review]

**Comment by graeme-a-stewart** [comment]
Thanks @eduardo-rodrigues - for chairing and the minutes 👍

**Comment by eduardo-rodrigues** [comment]
Thanks for the good eyes! I had missed those link issues.

**Pull request merged**
