### PR TITLE
Update profiles: educators w/ material

### PR DESCRIPTION
**Pull request by klieret**

### CODE REVIEW

**Comment by hegner** [comment]
@klieret - seems it still is testing against the wrong version of Graeme's profile. Can you make a quick update of this PR?

**Comment by klieret** [comment]
It should work now :)

**Comment by hegner** [comment]
I do not like the term "material" there. Wouldn't "author" or "writer" be better? Since that is the role, not the result?

**Review by michmx — APPROVED** [review]
I also agree that it is a better idea to switch from "material" to "author". But I see this must be done in all profiles that include the role, so let's go ahead as Kilian propose and fix that in a different PR.

**Pull request merged**
