### PR TITLE
WIP: Gsoc root ttree to rntuple proposal

### PR DESCRIPTION
**Pull request by aflp91**

### CODE REVIEW

**Review by hegner — APPROVED** [review]

**Comment by agheata** [comment]
I don't see the difficulty, duration and availability labels in this PR. We need to put the in place so they get visible in the final proposal page.

**Comment by aflp91** [comment]
Yes ! And it is why the PR was WIP!

**Comment by hegner** [comment]
ops. sorry!

**Comment by hegner** [comment]
I took it out again.

**Comment by agheata** [comment]
No problem, we can do this in a separate patch. But we'll need the logic to maybe transform these labels into text just below the title of the project proposal

**Comment by hegner** [comment]
That would be by changing 
https://github.com/HSF/hsf.github.io/blob/master/_layouts/gsoc_proposal.html
and using tags like {{ page.duration }}
Anyone of you signing up for that? Otherwise I will do this afternoon

**Comment by agheata** [comment]
Working on a couple of other items, and my afternoon is busy I'm afraid

**Comment by aflp91** [comment]
Another possibility is to add in `summary.md` and under the `Full list of proposals` lists by duration, by difficulties and by availability?

**Comment by agheata** [comment]
We may also do that to give a global overview (good idea), but this should appear also in the proposals for self-consistency

**Comment by hegner** [comment]
@jalopezg-r00t - thanks a lot. exactly what was needed
will review

**Pull request merged**
