### PR TITLE
Fix link checker link transformation

### LINKED ISSUE #1046: Link checker fails internal links
The link checker fails all links in recent PRs, see e.g. https://github.com/HSF/hsf.github.io/pull/1045 :+1: 

> All the link check failures seem to be the same kind as yesterday and all false positives. Maybe @klieret has an idea - it seems that {{site.baseurl}} is expanding to an empty string and then the URL checker is trying for an absolute path, instead of a relative one.

### PR DESCRIPTION
**Pull request by klieret**
Eventually supposed to fix #1046 . Trying things in the dark.

### CODE REVIEW

**Comment by hegner** [comment]
@klieret - what is the status of this? ready to go?

**Comment by klieret** [comment]
Hi @hegner : https://github.com/HSF/hsf.github.io/pull/1051 can be merged and includes a workaround fix.

This PR however doesn't provide any value other than documenting lot's of things that haven't worked.

**Comment by hegner** [comment]
@klieret - thanks. will look at the other one for now

**Comment by klieret** [comment]
(Closing this, because I don't have time to follow this further)

**Pull request closed without merging**
