### PR TITLE
Blog for the Symplectic Integrator Project in Geant4

### PR DESCRIPTION
**Pull request by divyanshtiwari237**
The blog contains all the information about my work done during the GSoC period.
cc @jonapost for review

### CODE REVIEW

**Comment by agheata** [comment]
@divyanshtiwari237 if possible, please use your GitHub avatar as in this [example](https://hepsoftwarefoundation.org/gsoc/blogs/2022/blog_HSF_TheAdmins.html)

**Comment by agheata** [comment]
@divyanshtiwari237 please ask your mentor to comment if this PR is OK with him

**Comment by jonapost** [comment]
I approve this blog post as a brief summary of Divyansh's work.

**Review by jonapost — APPROVED** [review]
This brief summary of the work provides a quick overview of Divyansh's work during GSoC 2022.

**Review by agheata — APPROVED** [review]

**Pull request merged**
