### PR TITLE
Coordination meeting, 2022-05-12

### PR DESCRIPTION
**Pull request by graeme-a-stewart**

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
Hi - if you have a chance to look, @drbenmorgan @amete... Otherwise I will hold my breath and self-merge.

**Review by drbenmorgan — APPROVED** [review]
Sorry for the delay @graeme-a-stewart, all looks good!

**Comment by graeme-a-stewart** [comment]
Thanks!

**Comment by amete** [comment]
Oops, I must've missed this, apologies. I see it is already merged but is it worth fixing the few typos that caught my eye?

**Pull request merged**
