### PR TITLE
Add information/announcement for PyHEP 2021

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Plan is to announce the workshop and open registration and abstract submission tomorrow morning :-).

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
This is ready for review modulo the possible update related to my question above.

**Review by graeme-a-stewart — APPROVED** [review]
LGTM Eduardo - I would say that now that GSoC is in more of an implementation phase we should also make this the centre column item on the web page

**Comment by graeme-a-stewart** [comment]
AFAICR things in `events` end up here: https://hepsoftwarefoundation.org/events.html. I think this is barely used.

Things in `announcements` go on the front page, which is far more useful.

**Comment by eduardo-rodrigues** [comment]
OK, thanks. So I do not update for https://hepsoftwarefoundation.org/events.html and we're done :-).

**Pull request merged**
