### PR TITLE
Coordination meeting minutes, 2019-09-26

### PR DESCRIPTION
**Pull request by graeme-a-stewart**

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
I don't really know what's wrong with the URL checker - the link works fine in my browser. Odd. Maybe needs a container refresh.

**Comment by drbenmorgan** [comment]
@graeme-a-stewart, I think that could just be LinkChecker's timeout? The link works locally for me, but a little slowly, so maybe LinkChecker is too impatient?

p.s. I've approved, but not sure what policy on merging is (do we require all reviewers approve?).

**Comment by graeme-a-stewart** [comment]
Hi @drbenmorgan - usually one approval is enough. The reason to put down a few reviewers is to hope that someone has time to do quickly...

The zero return code is odd, but I have seen it happen when something odd goes on in the SSL layer - updating certs or adding a specific certificate can cure that, but I don't have time to do it right now.

**Comment by graeme-a-stewart** [comment]
Or the check failure was a glitch... all looks good now

**Pull request merged**
