### PR TITLE
GSOC student

### PR DESCRIPTION
**Pull request by Tanmay-Malviya**
I want to work for your organization

### CODE REVIEW

**Comment by hegner** [comment]
Hello @Tanmay-Malviya ! 
Unfortunately your PR is a bit convoluted and I can hardly see what you wanted to add. Could you please rebase properly on the current main?
In any case - if you want to participate, please have a look at https://hepsoftwarefoundation.org/activities/gsoc.html - starting from Feb 7 we will have our list of projects to work on on that page. More details about timescales etc are given on the website as well.

**Comment by wdconinc** [comment]
> Unfortunately your PR is a bit convoluted

@hegner I think this is a case of ML4SCI.org still using a fork of the HSF page for their pages, asking their community for PRs with projects, and those PRs being routed against the HSF page. I propose to close this PR since not actually relevant to HSF, and to let the maintainer of ML4SCI know that they should probably break the fork link with HSF.

Cc @emanueleusai

**Comment by emanueleusai** [comment]
@wdconinc thanks for letting me know about this. I opened a ticket to GitHub to unfork the ML4SCI website repo. We can close this as we obviously don't want to merge the edits from the ML4SCI website into the HSF website.

**Comment by hegner** [comment]
This PR was meant for a different (forked) project. Thus closing.

**Pull request closed without merging**
