### PR TITLE
Absolute paths for link checker and baseURL

### PR DESCRIPTION
**Pull request by klieret**
In reference to #1046

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hello @klieret, cc @graeme-a-stewart and @hegner for website enhancements. I see this long-standing PR. It's rather short. Do you intend to finalise or else we close at this point?

**Comment by eduardo-rodrigues** [comment]
Hello @klieret, what is the status here? Let me also ping @graeme-a-stewart and @hegner since they are thinking about the new revamped site.

**Comment by jouvin** [comment]
Is this PR still relevant? I have the feeling that yes and it would be a good idea not to hardcode the host name of the web site? If yes, why we don't merge this PR is @klieret is not available to follow it up?

**Comment by eduardo-rodrigues** [comment]
Probably. I'm no expert but the changes seem small eough that somebody can review?

**Comment by graeme-a-stewart** [comment]
I can take a look, but I would say this wants a rebase first!

**Comment by graeme-a-stewart** [comment]
OK, this all looks good to me. Killian had set it to link check the whole site, but that took about an hour and we used to get badly burned by false positives when that was done on PRs. So I have reverted to the check of changed pages only. (It would be good to also have a workflow that triggers a whole site check, but that shouldn't be the normal workflow for PRs.)

**Review by graeme-a-stewart — APPROVED** [review]
Thanks a lot for this change @klieret!

**Pull request merged**
