### PR TITLE
add Jean-Roch Vlimant to ACTSTrackML project, add Caltech as an org

### PR DESCRIPTION
**Pull request by dhrou**
add Jean-Roch Vlimant to ACTSTrackML project, add Caltech as an org

### CODE REVIEW

**Comment by dhrou** [comment]
Hi, the CI failure seems due to 2 dead links somewhere in the site, nothing to do with my changes.
What should I do ?
Thanks
David

**Comment by aflp91** [comment]
CI errors have nothing to do with this PR: we could merge it.

**Comment by dhrou** [comment]
Sorry I had not seen you approved it. I just pushed a dummy change with a white space to re-trigger the CI

**Comment by dhrou** [comment]
Jean-Roch has not received the invitation. Is this happening ? How is it supposed to look like ?

**Comment by JavierCVilla** [comment]
@dhrou My apologies, I forgot to send him an invitation. He should have received it already, otherwise please let me know.

**Comment by JavierCVilla** [comment]
@dhrou is this already solved?

**Comment by dhrou** [comment]
solved, thanks
David

**Pull request merged**
