### PR TITLE
[GSoC2024] Clad+Kokkos project blogpost by Atell Krasnopolski

### PR DESCRIPTION
**Pull request by gojakuch**

### CODE REVIEW

**Comment by gojakuch** [comment]
project: [Implement differentiating of the Kokkos framework](https://hepsoftwarefoundation.org/gsoc/2024/proposal_Clad-Kokkos.html)

cc: @vgvassilev

**Comment by vvolkl** [comment]
> project: [Implement differentiating of the Kokkos framework](https://hepsoftwarefoundation.org/gsoc/2024/proposal_Clad-Kokkos.html)
> 
> cc: @vgvassilev
> 
> ps: my GSoC deadline is Nov, 4th, so I assume this should be merged before that, right? 🙏🙏

Thanks for the PR! There is no problem with the deadline, as long as you've opened it. But I'll anyway merge as soon as @vgvassilev approves.

**Comment by gojakuch** [comment]
> > project: [Implement differentiating of the Kokkos framework](https://hepsoftwarefoundation.org/gsoc/2024/proposal_Clad-Kokkos.html)
> > cc: @vgvassilev
> > ps: my GSoC deadline is Nov, 4th, so I assume this should be merged before that, right? 🙏🙏
> 
> Thanks for the PR! There is no problem with the deadline, as long as you've opened it. But I'll anyway merge as soon as @vgvassilev approves.

oh alright then, I just panicked that it needs to be merged before that :)

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
