### PR TITLE
profile update

### PR DESCRIPTION
**Pull request by pratyaksh177**
All profiles are arranged in same way.

### CODE REVIEW

**Comment by klieret** [comment]
Sorry, could you elaborate on what you're trying to achieve here?

**Comment by pratyaksh177** [comment]
Sir in profile section I have tried to  arranged all the persons details neatly.  @klieret

**Comment by klieret** [comment]
Hi @pratyaksh177 . I appreciate your efforts, but I unfortunately do not see the added benefit of this PR. Moreover, the formatting would most likely be overwritten when the profiles are synchronized with https://github.com/HSF/website-helpers.

**Comment by pratyaksh177** [comment]
Ok @klieret sir no worries

**Pull request closed without merging**
