### PR TITLE
Fixed image inclusion for mobile layout

### LINKED ISSUE #1247: Fix mobile layout of floating pictures
* **Required knowledge**: HTML, CSS

The floating pictures on https://hepsoftwarefoundation.org/workinggroups/training.html get very very small on a mobile layout. Instead they should just flow to "interrupt" the text.

### PR DESCRIPTION
**Pull request by Ahnaf-codes**
Resolves #1247 by making images responsive

### CODE REVIEW

**Comment by klieret** [comment]
Thanks a lot for working on this! However, when I naively resize the browser window, I'm getting this: 

image

which makes the text appear very awkard (because only two words per line). Is there a way to solve this? Or will the phone display be ok? (the screenshot you showed in the issue seemed OK)

**Comment by Ahnaf-codes** [comment]
Can you tell me what viewport width you're using? I can figure it out if I get the viewport width

**Comment by klieret** [comment]
Thank you :)  Do you mean these values:

```
./_layouts/default.html:    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">
./_layouts/meetings.html:    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">
```

**Comment by Ahnaf-codes** [comment]
No I meant the size of the screen. It's okay if you don't have it. But it may take a bit longer

**Comment by klieret** [comment]
But don't different phones have different screen sizes?

**Comment by Ahnaf-codes** [comment]
Yeah but I can resize my desktop window in responsive mode to see what the issue is.
So if I got an exact resolution I wouldn't have to play around with the resolution to get a good size

**Comment by klieret** [comment]
I think the viewport above is around 495px wide. And when I just checked on my 6" phone, the viewport was still smaller, I think.

**Comment by klieret** [comment]
Since this is definitely an improvement, let me go ahead and merge this!

Thanks again for your contributions @Ahnaf-codes

**Review by klieret — APPROVED** [review]

**Pull request merged**
