### PR TITLE
Training highlight ours

### PR DESCRIPTION
**Pull request by klieret**
Highlighting trainings organized/supported by HSF and some related improvements.

### CODE REVIEW

**Comment by hegner** [comment]
Hi @klieret ! Is this WIP or complete as PR?

**Comment by klieret** [comment]
Hi @hegner That should be complete like this :)

**Comment by hegner** [comment]
@klieret can you deal with the merge conflict?

**Comment by klieret** [comment]
> @klieret can you deal with the merge conflict?

Ah, thanks for making me aware of this!

**Comment by klieret** [comment]
Thanks a lot for the review @hegner

**Comment by hegner** [comment]
Hi @klieret - I need to squash this PR. Rebasing would not work because of the conflicts. OK with you?

**Comment by hegner** [comment]
OK. it seems you were quicker :-)

**Comment by graeme-a-stewart** [comment]
In general I favour to squash these PRs in anycase, as usually the intermediate commits are of no real long-term interest - but it's not a big issue (the only think I really care about is avoiding merge commits on master)

**Comment by klieret** [comment]
Hmm, if there's a lot of development in one PR, then having the single commits can be good to roll back things. And it's also better for git blame IMO. Commits are cheap anyway ;) 

I do prefer squashes if there's a lot of useless "FIX X in previous commit" commits, but these should ideally already be squashed by the user before pushing the branch or opening the PR.

**Comment by klieret** [comment]
Out of curiousity, why do you want to avoid merge commits? From my understanding they are the cleanest solution if there are merge conflicts.

**Comment by klieret** [comment]
Not that this is a hill to die on for me, I'm more asking out of curiosity ;)

**Comment by graeme-a-stewart** [comment]
Merge commits lead to a messy and irrelevant history (certainly for a website). Rebase and future generations will thank you 😄.

Most of our updates here are of the type (a) write new pages (b) get some review comments (c) make minor fixes... hence squashing usually makes sense. If the contributor rebased and squashed them it can be harder for the reviewer to check that what they asked to change did get fixed.

If there are significant changes per-commit then, yes, accepting the bundle can be useful (there are always exceptions!). However, it also makes the history longer and that can impede understanding.

In the end I'm also quite pragmatic about this!

**Pull request merged**
