### PR TITLE
proposal_IRIS-HEPawkwardgpu

### PR DESCRIPTION
**Pull request by jpivarski**
We think this is ready to be merged (@davidlange6 and @jpivarski). Thanks!

* Add IRIS-HEP 'awkwardgpu' proposal.

* Add IRIS-HEP 'princeton' organization.

* Add IRIS-HEP 'IRIS-HEP' project.

* Add IRIS-HEP logo.

### CODE REVIEW

**Comment by jpivarski** [comment]
> Looks good for me too, but the logo name doesn't follow conventions
> described in [instructions](https://hepsoftwarefoundation.org/gsoc/guideline.html) ("please name your logo PROJECTNAME-logo.png")

The name is currently `iris-hep-logo.png`; is the problem that `iris-hep` is not capitalized or that it has a hyphen or both?

In 2019, the IRIS-HEP project had a hyphen, but looking back, there were only two like that (IRIS-HEP and CernVM-FS).

**Comment by jpivarski** [comment]
In the last commit, I addressed @agheata's request to add mentors to gsoc/2020/mentors.md and I addressed @aflp91's request to format the logo name differently by capitalizing and removing the hyphen in IRIS-HEP.

I think it's all set now (even if removing the hyphen was unnecessary).

**Comment by aflp91** [comment]
> > Looks good for me too, but the logo name doesn't follow conventions
> > described in [instructions](https://hepsoftwarefoundation.org/gsoc/guideline.html) ("please name your logo PROJECTNAME-logo.png")
> 
> The name is currently `iris-hep-logo.png`; is the problem that `iris-hep` is not capitalized or that it has a hyphen or both?
> 
> In 2019, the IRIS-HEP project had a hyphen, but looking back, there were only two like that (IRIS-HEP and CernVM-FS).

Just this year we have proposed to uniformize the naming conventions  as "PROJECTNAME-logo.png"; but in order to be able to display previous years in the wiki we kept the old logo names in the images directory; so it's a bit confusing…

**Comment by jpivarski** [comment]
In the statement, "it needs to be 'PROJECTNAME-logo.png'," it's not clear to me whether you're saying all-caps is the important thing (although that's suggestive) or whether you're saying the lack of hyphens is the important thing (which is less clear), or both.

You could be totally clear with a regex: "it needs to match `/[A-Z0-9_]+-logo.png/`." If you're trying to regulate names, you'd have to do something like that (although the explanation of what characters are allowed could be in the text, instead of a regex). This is always an issue with documentation that puts substitution variables in the examples—readers of the documentation are unsure what aspects of the substitution variable is constant and what is variable...

**Comment by aflp91** [comment]
> In the statement, "it needs to be 'PROJECTNAME-logo.png'," it's not clear to me whether you're saying all-caps is the important thing (although that's suggestive) or whether you're saying the lack of hyphens is the important thing (which is less clear), or both.
> 
> You could be totally clear with a regex: "it needs to match `/[A-Z0-9_]+-logo.png/`." If you're trying to regulate names, you'd have to do something like that (although the explanation of what characters are allowed could be in the text, instead of a regex). This is always an issue with documentation that puts substitution variables in the examples—readers of the documentation are unsure what aspects of the substitution variable is constant and what is variable...

You are right! I'll put a PR to improve our  document…

**Pull request merged**
