### PR TITLE
Add twitter inset

### PR DESCRIPTION
**Pull request by klieret**
I don't manage to get it centered though...
image

### CODE REVIEW

**Comment by hegner** [comment]
@klieret @graeme-a-stewart - I think adding that we should change the overall layout of the first page which is a bit dated by now. Would both of you be interested in a little brainstorming this week?

**Comment by graeme-a-stewart** [comment]
Yes, definitely

**Comment by klieret** [comment]
Sure :)   Though I actually don't think the layout is so dated.

**Comment by hegner** [comment]
Correct. @klieret - can you join https://mattermost.web.cern.ch/ep-rd-software/channels/hsf-website ?

**Comment by klieret** [comment]
I think you'd first have to add me to the team. (Can't guarantee to look there too often though as it'd be the only thing I'm checking mattermost for atm)

**Comment by graeme-a-stewart** [comment]
Actually, the mattermost team should have been https://mattermost.web.cern.ch/signup_user_complete/?id=eykdjzkkrb8dmbbezbriksxthc (the HSF mattermost)

**Comment by graeme-a-stewart** [comment]
So I solved the centering issue by using a few padding columns like this:

```html
<div class="row">

  <div class="col-lg-3"></div>

  <div class="col-lg-6">
    <a class="twitter-timeline" style="margin: auto;" data-width="400" data-height="800" href="https://twitter.com/hepsoftfound?ref_src=twsrc%5Etfw">Tweets by hepsoftfound</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  </div>

  <div class="col-lg-3"></div>
</div>
```

But in my local preview (`bundler exec jekyll serve`) I don't get the feed of tweets - how did you manage that? A different web engine?

**Comment by klieret** [comment]
@graeme-a-stewart  Sometimes it takes a few seconds to load... (or you have to reopen it in a new tab or something...)

There's no extra build step or anything

**Comment by klieret** [comment]
image

**Comment by klieret** [comment]
I'm happy with this now, but we can always improve the layout of course... (and people will have to test it on mobile as well...)

**Comment by klieret** [comment]
I think I already fixed the link checker complaint in a recent PR

**Comment by klieret** [comment]
(I just rebased it to master)

**Comment by graeme-a-stewart** [comment]
> @graeme-a-stewart Sometimes it takes a few seconds to load... (or you have to reopen it in a new tab or something...)
> 
> There's no extra build step or anything

Yeah, I worked it out - I have social media tracking blocked by default in my browser, which stymies the loading of a twitter feed!

Looks good now (again, rebased after a PyHEP update to the centre column).

**Review by graeme-a-stewart — APPROVED** [review]

**Pull request merged**
