### PR TITLE
GSoC Proposal: Data compression for FASER project

### PR DESCRIPTION
**Pull request by cantel**
### Adding 2023 GSoC Proposal for FASER

Proposing a GSoC proposal for real-time data compression for the FASER experiment at the LHC.

Adding:
- New (2023) Organisation: unige (Geneva University)
- New project: FASER + faser logo
- New proposal: data compression for FASER, 2 new mentors

### CODE REVIEW

**Comment by cantel** [comment]
Hi @hegner @vvolkl @wdconinc ,
Here is the proposal for GSoC 2023 for the FASER experiment.

cheers,
Claire

**Comment by hegner** [comment]
@cantel - unfortunately your faserdaq link is only CERN internal. Do you have any publicly available equivalent? Thanks

**Comment by cantel** [comment]
Hi, sorry, had received further comments from colleagues, but open for review now, thanks!

**Review by vvolkl — APPROVED** [review]

**Comment by hegner** [comment]
@cantel - still the faserdaq link is not available from outside. do you have anything else available?

**Comment by hegner** [comment]
@cantel - thanks!

**Pull request merged**
