### PR TITLE
Addition of project for allpix squared

### PR DESCRIPTION
**Pull request by dhynds**
A proposal to develop multi-threading for allpix squared, hosted between CERN and Nikhef. A follow-on of the very successful work carried out last year as part of GSoC 2018

### CODE REVIEW

**Comment by dhynds** [comment]
Thanks for the quick reply: have updated the mentors list. I know the internal deadline is tomorrow, is there an issue if a mentor institute/email has to be updated in the coming days?

**Comment by JavierCVilla** [comment]
> I know the internal deadline is tomorrow, is there an issue if a mentor institute/email has to be updated in the coming days?

@dhynds It is not a problem, feel free to submit any modification that you may consider.

**Comment by JavierCVilla** [comment]
I asked @graeme-a-stewart to trigger travis again since some of the CI errors are related to this PR. Trying to figure out why it failed.

**Comment by JavierCVilla** [comment]
All checks passed, so I'm merging.

Thank you @graeme-a-stewart

**Comment by dhynds** [comment]
> > I know the internal deadline is tomorrow, is there an issue if a mentor institute/email has to be updated in the coming days?
> 
> @dhynds It is not a problem, feel free to submit any modification that you may consider.

Ok, great - and thanks a lot to all of you!

**Pull request merged**
