### PR TITLE
[GSoC] Add SWAN proposal

### PR DESCRIPTION
**Pull request by JavierCVilla**
* Mentors will be added to the list on a different PR together with other missing mentors

### CODE REVIEW

**Comment by JavierCVilla** [comment]
Thanks @aflp91, done

**Comment by JavierCVilla** [comment]
@aflp91 Can we wait until #465 gets merge? @diocas also submitted a SWAN logo and description, so I will adapt this PR after his.

**Comment by aflp91** [comment]
Sure! Thanks a lot …

**Comment by JavierCVilla** [comment]
@aflp91 Done, feel free to merge.

**Pull request merged**
