### PR TITLE
Fix a typo in Rucio title

### PR DESCRIPTION
**Pull request by aflp91**
We cannot put a colon in a title…

### CODE REVIEW

**Review by klieret — APPROVED** [review]

**Comment by aflp91** [comment]
@klieret : you are right! Let's @mlassnig decide…

**Comment by hegner** [comment]
thanks for spotting that !

**Review by mlassnig — APPROVED** [review]

**Comment by mlassnig** [comment]
Thanks, please merge :-)

**Comment by agheata** [comment]
Just for the record: you can use whatever characters if you write them as:
```
title: >
  Rucio: S3-compatible access interface for analysis facilities
```

**Pull request merged**
