### PR TITLE
GSOC'22 Week-0 Blog

### PR DESCRIPTION
**Pull request by Harshil-Jani**
Blog post describing my Community Bonding Period experience with CERN-HSF for the year 2022.

### CODE REVIEW

**Comment by klieret** [comment]
Hi @Harshil-Jani : A couple of spelling issues have been found. Click on the "pre-commit.ci" button above to see them. 

You can ignore the other issue which was introduced somewhere else and that I'll fix in a separate PR

**Comment by klieret** [comment]
Also, is there anyone who should review your PR? (like a mentor)

**Comment by amadio** [comment]
We are waiting for the CI to be fixed upstream, so that the changes can be properly tested before being merged. If merging can happen despite the CI failures, then we can proceed.

**Comment by klieret** [comment]
I've fixed the "Jekyll Relative URL HTML" failure; the reason the pre-commit still reports failure is because of the spelling issues, so if you go ahead and fix these, everything should be green :)

**Comment by amadio** [comment]
@Harshil-Jani Can you please look into the spelling issues as mentioned by @klieret? Thank you!

**Comment by Harshil-Jani** [comment]
Hi ! I have made the changes. Thanks for helping out @klieret @amadio

**Review by klieret — APPROVED** [review]

**Comment by amadio** [comment]
👍 Thanks for merging, @hegner.

**Comment by agheata** [comment]
@Harshil-Jani please update this blog:
- change the title to match your project (and not only the community bonding period)
- Add the relevant links to your contributions during the first half of the coding period

**Comment by Harshil-Jani** [comment]
Okay ! I will make appropriate changes soon @agheata . Thanks for notifying !

**Pull request merged**
