### PR TITLE
Sanchi blog

### PR DESCRIPTION
**Pull request by SanchiMittal**
Final blog added for Batch Generator Project.

Kindly review cc @lmoneta @agheata

### CODE REVIEW

**Comment by agheata** [comment]
@lmoneta can you please have a quick look?

**Review by sanjibansg — APPROVED** [review]
LGTM!

**Review by lmoneta — APPROVED** [review]
LGTM!

**Comment by SanchiMittal** [comment]
I have made minor changes of changing "MidTerm" to "Final Evaluation" and centering the image. I hope that is fine @agheata

**Review by agheata — APPROVED** [review]
LGTM

**Pull request merged**
